### ISSUE TITLE
websocket如何配置呢?

### ISSUE THREAD

**Issue by TaylorWenOne** [barbariska108/viabtc_exchange_server_docker-fixed#3]
你好，项目启动后，http正常访问，websocket无法连接
直连18091不行，是否需要修改config.json中的svr配置？尝试修改为tcp@0.0.0.0:8090还是一样的无法连接。
难道必须用nginx来代理吗？

**Comment by barbariska108** [comment]
@TaylorWenOne,

Yes, try to modify nginx proxy

**Comment by TaylorWenOne** [comment]
@barbariska108  thank you, i got it ,it works ,and i create a new fork which auto use nginx porxy in docker
[https://github.com/TaylorWenOne/viabtc_exchange_server_docker_with_nginx](url)
anthor question  , how can i add a new coin  and an exchange pair by  code，or  just one way to modify matchengine config.json ? i don't think it is grace

**Comment by barbariska108** [comment]
@TaylorWenOne, 

Yes, you can modify config.json with currency pairs.
And you can create a pull request with fix :)

**Comment by TaylorWenOne** [comment]
> @TaylorWenOne,
> 
> Yes, you can modify config.json with currency pairs.
> And you can create a pull request with fix :)
@barbariska108  only this way to add a new currency pairs?i think may be config.json could read from  mysql database that needn't restart service every time

**Comment by barbariska108** [comment]
> > @TaylorWenOne,
> > Yes, you can modify config.json with currency pairs.
> > And you can create a pull request with fix :)
> > @barbariska108  only this way to add a new currency pairs?i think may be config.json could read from  mysql database that needn't restart service every time

Actually yes...
Need full restart and rebuild a database...
